// <auto-generated />
namespace AICRDWEB.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AgregandonuevosCampoImagenAsociacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregandonuevosCampoImagenAsociacion));
        
        string IMigrationMetadata.Id
        {
            get { return "201702220334039_Agregando nuevos Campo Imagen Asociacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
